services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:test@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_data:
